apiVersion: v1
kind: ConfigMap
metadata:
  name: edc-validation-dashboard-config
data:
  NEXT_PUBLIC_API_URL: "https://edc-validation-dashboard.example.educloud"
  NEXT_PUBLIC_CLUSTER_NAME: "educloud"
  NEXT_PUBLIC_ENVIRONMENT: "educloud"
  NEXT_PUBLIC_OTEL_ENDPOINT: ""
  MVD_CONSUMER_CP_URL: "http://consumer-control-plane:8080"
  MVD_PROVIDER_CP_URL: "http://provider-control-plane:8080"
  MVD_CONSUMER_DP_URL: "http://consumer-data-plane:8080"
  MVD_PROVIDER_DSP_URL: "http://provider-control-plane:8082/api/dsp/2025-1"
  MVD_PROVIDER_ID: "did:web:identityhub.provider.svc.cluster.local%3A7083:provider"
  MVD_CONSUMER_IH_URL: "http://consumer-identityhub:7082/cs"
  MVD_PROVIDER_IH_URL: "http://provider-identityhub:7083/cs"
  MVD_ISSUER_URL: "http://issuer:8080/admin"
  MVD_API_KEY_HEADER: "X-Api-Key"
  MVD_MOCK_MODE: "off"
